name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build and test
    steps:
      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v1

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Test with Gradle
        run: ./gradlew --no-daemon --continue clean check

      - name: Generate test summary
        uses: test-summary/action@v2
        if: success() || failure()
        with:
          paths: '**/build/test-results/**/TEST-*.xml'